name: CI PullRequest Workflow

on:
  pull_request:
    branches: ["main", "release/*"]
    paths-ignore:      
    - '**/Chart.yaml'
    - '**/Makefile'
    - '**/README.md' 
    - '**/.gitignore'       
    - '**/workflows/**'

concurrency:
  group: cicd_pullrequest

jobs:
  set-matrix:
    runs-on: [k8s]  
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get matrix inputs
        id: set-matrix
        run: |
          echo matrix=$(git diff --name-only HEAD HEAD~1|egrep 'charts|apps' |awk -F '/' '{print $2}'|awk '!seen[$0]++' | jq -R -s -c 'split("\n") | map(select(length > 0))') >> $GITHUB_OUTPUT 
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }} 

  test:
    needs: [set-matrix]
    runs-on: [k8s]
    container:
      image: hitachi.jfrog.io/docker/pdso-bootstrap/pdso-node:20.5.0-bullseye-slim
      credentials:
        username: ${{ vars.PDSO_ARTIFACTORY_USERNAME }}
        password: ${{ secrets.PDSO_ARTIFACTORY_TOKEN }}   
    name: '${{ matrix.project }} test'    
    strategy:    
      matrix:
        project: ${{ fromJson(needs.set-matrix.outputs.matrix) }}
    steps: 
      - name: Test
        uses: pentaho/pentaho-composite-actions@test
        id: test
        with:
          projectName: ${{ matrix.project }}    

  security:
    needs: [set-matrix, test]
    runs-on: [k8s]    
    permissions: write-all 
    name: '${{ matrix.project }} security suite'    
    strategy:
      matrix:
        project: ${{ fromJson(needs.set-matrix.outputs.matrix) }}
    steps: 
      - name: Security
        uses: pentaho/pentaho-composite-actions@security
        id: security
        with:
          projectName: ${{ matrix.project }}
          paToken: ${{ secrets.HV_ACTIONS_GIT_TOKEN }}
          isSonar: false
          globalArtifactoryUser: ${{ vars.PDSO_ARTIFACTORY_USERNAME }}
          globalArtifactoryToken: ${{ secrets.PDSO_ARTIFACTORY_TOKEN }} 


  slack:
    needs: [set-matrix, test, security]
    if: ${{ always() && contains(needs.*.result, 'failure') }}
    runs-on: [k8s] 
    name: 'slack notify'    
    steps: 
      - name: Slack
        uses: pentaho/pentaho-composite-actions@slack
        id: slack
        with:
          slackWebhookUrl: ${{ secrets.PDSO_SLACK_WEBHOOK }}  
